repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-json
    - id: check-added-large-files
    - id: detect-aws-credentials
    - id: mixed-line-ending
