version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Prepare Python environment
          command: |
            pip3 install -r ~/repo/requirements.txt --user
      - run:
          name: Install Pulumi CLI
          command: |
            curl -L https://get.pulumi.com/ | bash -s
            echo 'export PATH=${HOME}/.pulumi/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Login to Pulumi
          command: |
            export PULUMI_ACCESS_TOKEN=${PULUMI_ACCESS_TOKEN}
            pulumi login --cloud-url https://api.pulumi.com
      - run:
          name: Pulumi configurations
          command: |
            pulumi stack select dev
            pulumi config set aws:region us-east-1
            pulumi config set tagEnvironment dev
            pulumi config set tagNamespace nakt
            pulumi config set tagProjectName pulumitest
            pulumi config set connectInstanceId test
            pulumi config set connectContactFlowId test
            pulumi config set connectSourcePhoneNumber 0
      - run:
          name: Exec preview command
          command: |
            pulumi plugin install resource aws v1.4.0
            pulumi plugin ls
            pulumi preview --stack dev
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master

